controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
video_route:
    path: /videos/{publicite.mp4}
    controller: App\Controller\VideoController::show